[build]
  functions = "netlify/functions"

[functions]
  # Standard function timeout (for immediate responses)
  timeout = 26

[functions."deepseek-chat"]
  # Direct API calls for short responses (26s max)
  timeout = 26

[functions."background-deepseek"]
  # Background function for mystical rituals (15 minutes)
  timeout = 900

[functions."check-ritual"]
  # Quick polling endpoint
  timeout = 10

[functions."fal-kokoro-tts"]
  timeout = 60

[functions."fal-whisper-stt"]
  timeout = 60

# CORS headers for all functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
